### ISSUE TITLE
add another example usage

### ISSUE THREAD

**Issue by marsom** [swade1987/deprek8ion#10]
another example usage, which I prefer:

`cat /demo/ingress.yaml | docker run --rm -i quay.io/swade1987/deprek8ion:1.1.7 conftest test -p /policies -`

you dont need any volumes in this case, and this is very useful i.e. in building pipelines. furdermore you can diredtly pipe out a kubectl get ... command.

**Comment by swade1987** [comment]
Hey @marsom PRs to the documentation are welcome.
