### ISSUE TITLE
Publish policies to ArtifactHub

### ISSUE THREAD

**Issue by tylerauerbeck** [swade1987/deprek8ion#17]
Although still in alpha, looks like you can publish OPA policies to [ArtifactHub](https://artifacthub.io). Would be good to see deprek8ion policies there to be able to pull down.

**Comment by swade1987** [comment]
Closing as hosted at https://artifacthub.io/packages/opa/deprek8ion/deprek8ion

**Comment by fredgate** [comment]
@swade1987  How do you use policies hosted at `artifacthub.io` ?

I would like to download them and use them with `conftest` :
```
conftest pull https://artifacthub.io/packages/opa/deprek8ion/deprek8ion
```
but in the downloaded `policy` directory I get a HTML file instead of Rego files.

**Comment by swade1987** [comment]
@tegioz is this something you could advise on please?

**Comment by tegioz** [comment]
Hi 👋 

I think the best way to proceed would be to provide some [installation instructions in the package metadata file](https://github.com/artifacthub/hub/blob/00d89b28fe90713cdf4ed421c96fe07912cb81fb/docs/metadata/artifacthub-pkg.yml#L31-L34). When that information is available, we display a `INSTALL` button on the UI that will display those instructions to users. For other package kinds that have a generic way of installation (like Helm charts), we provide the installation instructions automatically.

This would be an example of installation instructions for a Keptn instegration provided by the publisher:

<img width="2044" alt="Screen Shot 2021-08-21 at 10 26 37" src="https://user-images.githubusercontent.com/1213902/130315842-bd2885e9-588d-4dc2-b4ae-9cb4335281fd.png">

<img width="2044" alt="Screen Shot 2021-08-21 at 10 26 52" src="https://user-images.githubusercontent.com/1213902/130315845-a3c6fb39-4f93-4abf-aed0-6e47a076d760.png">

Please keep in mind that Artifact Hub doesn't really hosts artifacts, only metadata about them. Our main goal is to make it easier for users to discover and explore content, but the installation instructions should point to the source, not Artifact Hub.

Hope this helps 🙂

**Comment by fredgate** [comment]
I was new to Artifact hub, and I came to understand that it only contained the metadata and not the artifacts themselves. Indeed it would be good to explain how to install these artefacts (Rego rules).
Here is the command that I used : `conftest pull git::https://github.com/swade1987/deprek8ion.git//policies`

**Comment by fredgate** [comment]
On the other hand, it would be good when a policy is modified, that a new publication is visible on artifact hub.
This is currently not the case because the last visible release is the 0.1.0 of july 27, 2020 while the rules have since been modified.

https: //github.com/swade1987/deprek8ion/blob/master/policies/artifacthub-pkg.yml

**Comment by fredgate** [comment]
What do you think @swade1987 ?

**Comment by swade1987** [comment]
@fredgate it makes sense for the version to upgrade when changes are made, is this possible @tegioz ?

**Comment by tegioz** [comment]
This is something that needs to be managed manually by the publisher @swade1987. Artifact Hub doesn't inspect changes at the git repo level actually, only in the AH metadata files provided. Also, we wouldn't know if you wanted to publish a release, what version to use, etc. 

It'd be great if you could update the version in the metadata file and even provide some notes for the changelog when you think it makes sense. This way we would notify users subscribed to your package in AH when the new release is available, letting them know what changed. You can even maintain multiple versions of your packages if you wish so. For more details please see the [OPA section](https://artifacthub.io/docs/topics/repositories/#opa-policies-repositories) in the repositories guide and the [metadata file reference](https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-pkg.yml).

**Comment by fredgate** [comment]
This is interesting. I understand that the publisher must update the `artifacthub-pkg.yml` file in its git repository. But next what happen :
- artifactoryhub will regularly fetch this file and check for changes ?
- the publisher must do an action on the artifactoryhub website ?
- the CI of project can call an API of artifactoryhub to trigger changes detection ?

**Comment by tegioz** [comment]
> - artifactoryhub will regularly fetch this file and check for changes ?

This one 😉 We poll all repositories regularly (every 30 mins at the moment) and index new packages and versions available in the repository. There are more than 1k at the moment and growing! Some have hundreds of packages and thousands of versions, others only one.

[https://artifacthub.io/stats](https://artifacthub.io/stats).

**Comment by swade1987** [comment]
@fredgate I am looking to potentially re-work the whole setup of this repository based on https://github.com/swade1987/deprek8ion/discussions/32 would love your input if possible. 

Additionally, if you'd be interested in pairing on a restructure I would be more than happy to have some assistance.
