### ISSUE TITLE
Usage suggestions?

### ISSUE THREAD

**Issue by webframp** [swade1987/deprek8ion#2]
These policies look really useful, this is a great use case for rego!

Can you share how you are you using these currently? Is it with an admission controller like OPA Gatekeeper or some other job/process in your deployment pipeline?

**Comment by swade1987** [comment]
Hi @webframp please see my blog post https://medium.com/@swade1987/deprek8ion-staying-ahead-of-k8s-api-deprecations-a378aed8d0a4 for more information. If you want further clarification please don’t hesitate to reach out.

**Comment by webframp** [comment]
That’s perfect, thanks!

**Comment by swade1987** [comment]
@webframp also added a docker container now with a usage example on the main README.
