### ISSUE TITLE
Removal of admissionregistration.k8s.io/v1beta1 has been retargeted to 1.22

### ISSUE THREAD

**Issue by cmur2** [swade1987/deprek8ion#20]
Hi, I was having a look at https://github.com/swade1987/deprek8ion/blob/master/policies/kubernetes-1.19.rego and wanted to learn more about the removal of `admissionregistration.k8s.io/v1beta1` but the https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md did not include any mention of that.

Finally I found https://github.com/kubernetes/kubernetes/issues/82021 which tells that this particular removal is now planned for K8s 1.22. I think the policy files should be updated, what do you think?

**Comment by swade1987** [comment]
@cmur2 100% we should move these to 1.22 if you have the time PRs are welcome if not I will get to it as soon as possible.

**Comment by cmur2** [comment]
@swade1987 ok, did it in https://github.com/swade1987/deprek8ion/pull/22 (I'm not entirely sure about the correct usage of `warn` vs `deny` so feel free to improve that)
