### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by dmourao** [swade1987/deprek8ion#27]
I've noticed that there are newer versions of the docker image built from this project repo (https://console.cloud.google.com/gcr/images/swade1987/EU/deprek8ion?gcrImageListsize=30).

However, i could not match image tag (eu.gcr.io/swade1987/deprek8ion:1.1.32) with the changes here (any rule fixed? conftest updated? etc). 
The project is abandoned for community or the source-of-truth for provided container images is another repo ?

**Comment by swade1987** [comment]
The image tag is fixed at `1.1.<build number>` the repo is still being actively maintained. 

If I am missing any deprecations please let me know and I will update accordingly.
